displayName=Instance Party Pings
author=willzero123
description=Ping tiles in different instances of the same map, like the Colosseum or the Inferno
tags=party,ping,tile,instance,colosseum,inferno,coaching
version=1.0.1
plugins=com.instancepartypings.InstancePartyPingsPlugin
build=standard
